[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/01-gallery.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/goit-js-hw-08/02-video.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/goit-js-hw-08/03-feedback.html"
  status = 200
  force = true
